### ISSUE TITLE
Убрать автоудаления юзеров

### ISSUE THREAD

**Issue by SerafimArts** [codersclub/forum#127]
Валера одобрил: http://forum.sources.ru/index.php?showtopic=377600&view=findpost&p=3473724 Где оно находится, я хз, перелопатил пол форума. Просьба Юре\Мише тыкнуть меня носом.

**Comment by SerafimArts** [comment]
https://github.com/codersclub/forum/commit/accfeb1019be9541a61bd947cab4042faa8ea8c6 иссью закрывать?

**Comment by Jureth** [comment]
ясное дело

**Comment by SerafimArts** [comment]
Хм. А проблема решена, не? Я вроде видел где-то коммит...
