### ISSUE TITLE
Не обновляется текст ссылки "вопрос решен"

### ISSUE THREAD

**Issue by negram** [codersclub/forum#213]
Статус темы изменяется, а текст ссылки так и остаёнся "вопрос решен" до обновления страницы

**Comment by Jureth** [comment]
ошибки в консоли браузера?

**Comment by Jureth** [comment]
А вообще оно сейчас не дружит с выводом монолога, так что если эта ошибка есть только на нексте и девеле, то проблема скорее всего в этом.

**Comment by negram** [comment]
Да, действительно. На боевом работает. Правда, "полужирность" шрифта не меняется :)

**Comment by Jureth** [comment]
с полужирностью вроде - да, баг, но там это просто лечится
