### ISSUE TITLE
Forum to PHP7

### ISSUE THREAD

**Issue by lookingupdate** [codersclub/forum#234]
Greets. Is your work on Forum files for IPB 1.2 for PHP 7 or 5?

**Comment by Jureth** [comment]
It was long before PHP 7 even released.

**Comment by lookingupdate** [comment]
Anyone still maintaining for that version of IPB 1.3?

**Comment by negram** [comment]
Hey @lookingupdate, this is fork of IPB 1.2. In other words this is far different from the initial forum engine.
Currently it works on PHP 5.6 but most of the features work on PHP 7.1. If you find an issue, please don't hesitate opening a ticket.

**Comment by lookingupdate** [comment]
Thank you so much for responding. Yes, the language function in the function.php does not work right in 7.1. Is there a way we can Email?

**Comment by negram** [comment]
@lookingupdate, sure. Please email me at mikhail.galanin@yahoo.com

**Comment by lookingupdate** [comment]
@negram, thanks much I just emailed you please check spam folder in case it goes there and put a filter so it goes to your inbox. Subject contains: "...PHP7".
